export var lang = {

    //Preklad do slovenčiny

    // Komponenty a súčiastky

    slovak: {
        Resistor: "Rezistor",
        Capacitor: "Kondenzátor",
        Inductor: "Cievka",
        Variable_resistor: "Nastaviteľný rezistor",
        Photoresistor: "Fotorezistor",
        Thermistor: "Termistor",
        Ground: "Zem",
        DC_Source: "DC Zdroj",
        AC_Source:"AC Zdroj",
        Voltmeter: "Voltmeter",
        Ammeter: "Ampérmeter",
        Ohmmeter: "Ohmmeter",
        Diode: "Dióda",
        NPN: "NPN Tranzistor",
        PNP: "PNP Tranzistor",
        MOSFET_N: "MOSFET-N",
        MOSFET_P: "MOSFET-P",
        LED: "LED",
        Meters: "Meracie Prístroje",
        Passive: "Pasívne Súčiastky",
        Sources: "Zdroje",
        Active: "Aktívne Súčiastky",
        Logical: "Logické Brány",
        Not: "NOT Brána",
        Or: "OR Brána",
        And: "AND Brána",
        Nor: "NOR Brána",
        Nand: "NAND Brána",
        Xor: "XOR Brána",
        Xnor: "XNOR Brána",
        Inputs: "Logické Vstupy",
        LowInput: "Logická Nula",
        HighInput: "Logická Jednotka",
        ClockGen: "Generátor Impulzov",
        SequenceGen: "Generátor Sekvencie",
        ToggleSwitch: "Vypínač",
        Outputs: "Logické Výstupy",
        Bulb: "Žiarovka",
        LogicalOutput: "Logický Výstup",
        Labels: "Označenia",
        Text: "Text",
        Box: "Skupina",
        Line: "Čiara",
        Label: "Štítok",
        Tools: "Nástroje",
        DigitalChips: "Digitálne Čipy",
        SevenSegDecoder: "7 Segmentový Dekodér",
        SevenSegDisplay: "7 Segmentový Displej",
        D_FlipFlop: "D Preklápací Obvod",
        T_FlipFlop: "T Preklápací Obvod",
        JK_FlipFlop: "JK Preklápací Obvod",
        Latch: "Latch",
        Multiplexor: "Multiplexor",
        Demultiplexor: "Demultiplexor",
        Counter: "Počítadlo",
        RingCounter: "Kruhové Počítadlo",
        DecimalDisplay: "Desiatkový Displej",
        HalfAdder: "Polovičná Sčítačka",
        FullAdder: "Úplná Sčítačka",
        SIPOregister: "SIPO Register",
        ClockCounter: "Počítadlo Impulzov",
        BinarySwitch: "Binárny Prepínač",
        LEDarray: "LED Pole",
        RGBLED: "RGB LED",
        Oscilloscope: "Osciloskop",
        Bus: "Zbernica",
        CustomLogic: "Vlastná Súčiastka",



        // Označenia tlačidiel, menu, nastavení

        Welcome: "Vitajte v LogicSim!",
        About: "O programe",
        News: "Novinky",
        Circuits: "Obvody",
        Docs: "Dokumentácia",
        SignIn: "Prihlásiť sa",
        Enter: "Zadať",
        Github: "GitHub",
        Cancel: "Zrušiť",
        Close: "Zavrieť",
        Save: "Uložiť",
        Dont_save: "Neuložiť",
        projectTitle: "Zadaj názov projektu",
        Options: "Nastavenia",
        themeText: "Zmeň farebný motív",
        languageText: "Zmeň jazyk",
        displayText: "Európske súčiastky",
        valuesText: "Ukáž hodnoty komponentov",
        showAlerts: "Ukáž upozornenia",
        partsPosition: "Zmeň stranu menu komponentov",
        grid: "Ukáž štvorcovú mriežku",
        Dark_theme: "Tmavá",
        Light_theme: "Svetlá",
        Red_theme: "Červená",
        Blue_theme: "Modrá",
        Circuit_netlist: "Textový zoznam obvodu",
        VoltageColor: "Zmeniť farbu napätia",
        UntitledCircuit: "Bez názvu",
        StartTutorial: "Začať tutoriál",
        SkipTutorial: "Preskočiť",
        Show: "Znova nezobrazovať",
        Next: "Ďalej",
        Previous: "Späť",
        Finish: "Dokončiť",
        ZoomIn: "Priblížiť",
        ZoomOut: "Oddialiť",
        Rotate: "Otočiť",
        Delete: "Zmazať",
        Clone: "Kopírovať",
        Center: "Centrovať",
        MoveEditor: "Posúvať Editor",
        Edit: "Upraviť",
        RemoveWire: "Zmazať Prepojenie",
        Apply: "Použiť",
        EditNode: "Upraviť Svorku",
        EditComponent: "Upraviť Súčiastku",
        AddTo: "Pridať Do:",
        SignalColor: "Farba Signálu:",
        Ok: "Ok",
        EditOscilloscope: "Upraviť Osciloskop",
        ChooseScope: "Vyberte Kanál:",
        Amplitude: "Amplitúda:",
        Color: "Farba:",
        Reverse: "Invertovať:",
        Toggle: "Prepnúť",
        RemoveFromChannel: "Odstrániť signál z kanála:",
        ComponentName: "Názov Súčiastky:",
        NumOfInputs: "Počet Vstupov:",
        NumOfOutputs: "Počet Výstupov:",
        SetColor: "Nastav Farbu:",
        SetPeriod: "Nastav Periódu CLK v ms:",
        NumOfBits: "Počet Bitov:",
        SetSequence: "Nastav Sekvenciu:",
        SetClockCount: "Nastav Hodnotu:",
        SetNumOfRows: "Počet Riadkov:",
        SetNumOfCols: "Počet Stĺpcov:",
        SelectChannel: "Vyberte Kanál",
        SelectTheme: "Vyberte Tému",
        SelectLanguage: "Vyberte Jazyk",
        DefinitionInputs: "Vstupy:",
        DefinitionOutputs: "Výstupy:",
        SetLabel: "Označenie:",
        RemoveLabel: "Odstrániť Označenie:",
        showNodes: "Prepínať svorky počas simulácie",

        // Obvody

        Circuits: "Obvody",
        SampleCir1: "Exkluzívny OR (XOR)",
        SampleCir2: "Väčšinová logika",
        SampleCir3: "Polovičná Sčítačka",
        SampleCir4: "Úplná Sčítačka",
        SampleCir5: "Dekóder 1 zo 4",
        SampleCir6: "Delenie Dvomi",
        SampleCir7: "Delenie Tromi",
        SampleCir8: "Prioritný Kódovač",
        SampleCir9: "SIPO",
        SampleCir10: "PISO",
        SampleCir11: "Smajlík",
        SampleCir12: "Počítadlo Hore-Dole",
        SampleCir13: "SR Preklápací Obvod",
        SampleCir14: "4-Bit Počítadlo",
        SampleCir15: "8-Bit Počítadlo",
        SampleCir16: "3-Bit Grayov Kód",
        SampleCir17: "Časovaný SR Preklápací Obvod",
        SampleCir18: "D Preklápací Obvod spustený na hrane",
        SampleCir19: "Master-Slave Preklápací Obvod",
        SampleCir20: "Synchrónne Počítadlo",
        SampleCir21: "2-Bit Komparátor",
        SampleCir22: "74181-ALU",
        
        // Oznamy a texty používateľom

        Error: "Chyba",
        Warning: "Pozor",
        Info: "Info",
        Success: "Úspech",


        mainFunctions: "Hlavné Funkcie",

        circuitDesign: "Návrh Obvodov",
        circuitDesignText: "Užívatelia môžu jednoducho navrhovať obvody prostredníctvom drag-and-drop rozhrania.",

        simulation: "Simulácia v Reálnom Čase",
        simulationText: "Obvody sú simulované v reálnom čase, s možnosťou pozorovania hodnôt na jednotlivých výstupoch a vstupoch.",

        tutorial: "Tutoriál a Inštrukcie",
        tutorialText: "Aplikácia obsahuje tutoriál a krok-za-krokom inštrukcie pre nových užívateľov.",

        projectName: "Názov projektu",
        author: "Autor",
        aboutText: "Tento maturitný projekt predstavuje interaktívny simulátor logických obvodov, ktorý umožňuje študentom a nadšencom z oblasti elektroniky a informatiky experimentovať s digitálnymi obvodmi v reálnom čase. Vytvorený v jazykoch JavaScript, HTML a CSS, tento nástroj využíva knižnicu Konva.js pre vizualizáciu komponentov a obvodov na plátne.",

        saveText: "Ste si istý, že chcete pokračovať bez uloženia aktuálneho projektu?",
        Save_project: "Uložiť projekt?",

        WelcomeTitle: "Simulátor Logických Obvodov",
        WelcomeText: "Vitajte na stránke LogicSim! Učebná pomôcka pre simuláciu logických obvodov. Či už ste skúsený nadšenec elektroniky alebo zvedavý začiatočník. S intuitívnym rozhraním a rozsiahlou knižnicou komponentov, môžete oživiť svoje nápady a pozorovať simuláciu logických obvodov v reálnom čase. Dúfam, že Vám tento simulátor pomôže lepšie pochopiť ako fungujú logické obvody. Veselé simulovanie!",

        ChangeSettings: "Zmena nastavení",
        Tutorial1: "Jednoduchá zmena nastavení celej stránky. Je možné meniť farebný motív, jazyk a mnoho ďaľších nastavení pre prácu v editore.",

        CircuitEditor: "Práca v editore",
        Tutorial2: "Používatelia môžu približovať a odďalovať pohľad. Rovnako je môžné sa nekonečne pohybovať vo všetkých smeroch.",

        AddComponents: "Prídavanie súčiastok",
        Tutorial3: "Rýchle pridávanie súčiastok z knižnice. Na výber je až 32 jedninečných súčiastok.",

        EditComponents: "Úprava súčiastok",
        Tutorial4: "Používatelia môžu voľne editovať všetky súčiastky meniť ich pozíciu, rotáciu a odstrániť nepotrebné súčiastky. Kliknutím pravým na súčiastku ju ďalej upravíte.",

        AddWires: "Prepájanie súčiastok",
        Tutorial5: "Pri kliknutí na akékoľvek dve svorky sa vytvorí spojenie medzi dvomi súčiastkami. Pri kreslení spojenia z výstupu je možné pravým kliknutím meniť tvar prepojenia.",

        Simulate: "Simulácia obvodov",
        Tutorial6: "Animovaná simulácia akéhokoľvek logického obvodu. Simulácia sa spustí a zastaví len jediným kliknutím.",

        OscilloscopeSettings: "Osciloskop a priebeh signálu",
        Tutorial7: "Pridávanie akejkoľvek svorky pravým kliknutím do osciloskopu. Signál je možné upraviť pravým kliknutím na osciloskop.",

        SaveAndLoad: "Uloženie a načítanie obvodu",
        Tutorial8: "Zapojený obvod sa jednoducho uloží v JSON formáte, ktorý si používatel môže sám ďalej upraviť v textovej forme alebo načítať a upravovať v editore.",


        GithubPage: "Open source zdrojový kód",
        Tutorial9: "Celý zdrojový kód aplikácie je dostupný na mojej GitHub stránke.",


        WireLoop: "Bol zistený skrat v obvode!",
        IncorrectTitle: "Názov musí mať aspoň 4 znaky a menej ako 30!",
        CorrectTitle: "Názov sa zmenil!",
        DownloadCompleted: "Sťahovanie obvodu sa podarilo!",
        WrongOutput: "Výstup je nesprávne zapísaný",
        WrongInput: "Nesprávne zvolená hodnota!",
        EditDisabled: "Pridávanie súčiastok a mazanie prepojení nie je možné pri spustenej simulácií!",
    },
    
    //Preklad do angličtiny

    english: {
        // Komponenty a grafické widgety do editora

        Resistor: "Resistor",
        Capacitor: "Capacitor",
        Inductor: "Inductor",
        Variable_resistor: "Variable Resistor",
        Photoresistor: "Photoresistor",
        Thermistor: "Thermistor",
        Ground: "Ground",
        DC_Source: "DC Source",
        AC_Source:"AC Source",
        Voltmeter: "Voltmeter",
        Ammeter: "Ammeter",
        Ohmmeter: "Ohmmeter",
        Diode: "Diode",
        NPN: "NPN Transistor",
        PNP: "PNP Transistor",
        MOSFET_N: "MOSFET-N",
        MOSFET_P: "MOSFET-P",
        LED: "LED",
        Meters: "Meters",
        Passive: "Passive",
        Sources: "Sources",
        Active: "Active",
        Logical: "Logical Gates",
        Not: "NOT Gate",
        Or: "OR Gate",
        And: "AND Gate",
        Nor: "NOR Gate",
        Nand: "NAND Gate",
        Xor: "XOR Gate",
        Xnor: "XNOR Gate",
        Inputs: "Logical Inputs",
        LowInput: "Low Input",
        HighInput: "High Input",
        ClockGen: "Clock Generator",
        SequenceGen: "Sequence Generator",
        ToggleSwitch: "Toggle Switch",
        Outputs: "Logical Outputs",
        Bulb: "Light Bulb",
        LogicalOutput: "Logical Output",
        Labels: "Labels",
        Text: "Text",
        Box: "Box",
        Line: "Line",
        Label: "Label",
        Tools: "Tools",
        DigitalChips: "Digital Chips",
        SevenSegDecoder: "7 Segment Decoder",
        SevenSegDisplay: "7 Segment Display",
        D_FlipFlop: "D Flip Flop",
        T_FlipFlop: "T Flip Flop",
        JK_FlipFlop: "JK Flip Flop",
        Latch: "Latch",
        Multiplexor: "Multiplexor",
        Demultiplexor: "Demultiplexor",
        Counter: "Counter",
        DecimalDisplay: "Decimal Display",
        RingCounter: "Ring Counter",
        HalfAdder: "Half Adder",
        FullAdder: "Full Adder",
        SIPOregister: "SIPO Register",
        ClockCounter: "Clock Counter",
        BinarySwitch: "Binary Switch",
        LEDarray: "LED Array",
        RGBLED: "RGB LED",
        Oscilloscope: "Oscilloscope",
        Bus: "Bus",
        CustomLogic: "Custom Logic",

        // Označenia tlačidiel, menu, nastavení

        Welcome: "Welcome to LogicSim!",
        About: "About",
        News: "News",
        Circuits: "Circuits",
        Docs: "Documentation",
        SignIn: "Sign In",
        Enter: "Enter",
        Github: "GitHub",
        Cancel: "Cancel",
        Close: "Close",
        Save: "Save",
        Dont_save: "Don't save",
        projectTitle: "Enter your project title",
        Options: "Options",
        themeText: "Change color theme",
        languageText: "Change language",
        displayText: "European parts",
        valuesText: "Show component values",
        partsPosition: "Change components menu position",
        showAlerts: "Show alerts",
        grid: "Show grid",
        Dark_theme: "Dark",
        Light_theme: "Light",
        Red_theme: "Red",
        Blue_theme: "Blue",
        Circuit_netlist: "Circuit netlist",
        VoltageColor: "Change voltage color",
        UntitledCircuit: "Untitled circuit",
        StartTutorial: "Start tutorial" ,
        SkipTutorial: "Skip tutorial",
        Show: "Don't show again",
        Next: "Next",
        Previous: "Previous",
        Finish: "Finish",
        ZoomIn: "Zoom-In",
        ZoomOut: "Zoom-Out",
        Rotate: "Rotate",
        Delete: "Delete",
        Clone: "Copy",
        Center: "Center",
        MoveEditor: "Drag Editor",
        Edit: "Edit",
        RemoveWire: "Remove Wire",
        Apply: "Apply",
        EditNode: "Edit Node",
        EditComponent: "Edit Component",
        AddTo: "Add To Scope:",
        SignalColor: "Signal Color:",
        Ok: "Ok",
        EditOscilloscope: "Edit Oscilloscope",
        ChooseScope: "Choose Channel To Edit:",
        Amplitude: "Amplitude:",
        Color: "Color:",
        Reverse: "Reverse:",
        Toggle: "Toggle",
        RemoveFromChannel: "Remove Signal From Channel:",
        ComponentName: "Component Name:",
        NumOfInputs: "Number Of Inputs:",
        NumOfOutputs: "Number Of Outputs:",
        SetColor: "Set Color:",
        SetPeriod: "Set CLK Period in ms:",
        NumOfBits: "Set Number Of Bits:",
        SetSequence: "Set Sequence:",
        SetClockCount: "Set Clock Count:",
        SetNumOfRows: "Set Number Of Rows:",
        SetNumOfCols: "Set Number Of Cols:",
        SelectChannel: "Select Channel",
        SelectTheme: "Select Theme",
        SelectLanguage: "Select Language",
        DefinitionInputs: "Inputs:",
        DefinitionOutputs: "Outputs:",
        SetLabel: "Label:",
        RemoveLabel: "Remove Label:",
        showNodes: "Toggle nodes during simulation",

        // Obvody

        Circuits: "Circuits",
        SampleCir1: "Exclisive OR",
        SampleCir2: "Majority Logic",
        SampleCir3: "Half Adder",
        SampleCir4: "Full Adder",
        SampleCir5: "1-of-4 Decoder",
        SampleCir6: "Divide By Two",
        SampleCir7: "Divide By Three",
        SampleCir8: "Priority Encoder",
        SampleCir9: "SIPO",
        SampleCir10: "PISO",
        SampleCir11: "Smiley",
        SampleCir12: "Up-Down Counter",
        SampleCir13: "SR Flip-Flop",
        SampleCir14: "4-Bit Counter",
        SampleCir15: "8-Bit Counter",
        SampleCir16: "3-Bit Gray Code",
        SampleCir17: "Clocked SR Flip-Flop",
        SampleCir18: "Edge Triggered D Flip-Flop",
        SampleCir19: "Master-Slave Flip-Flop",
        SampleCir20: "Synchronous Counter",
        SampleCir21: "2-Bit Comparator",
        SampleCir22: "74181-ALU",
        
        // Oznamy a texty používateľom

        Error: "Error",
        Warning: "Warning",
        Info: "Info",
        Success: "Success",

        mainFunctions: "Main Functions",

        circuitDesign: "Circuit Design",
        circuitDesignText: "Users can easily design circuits through a drag-and-drop interface.",

        simulation: "Real Time Simulation",
        simulationText: "Circuits are simulated in real time, with the possibility of observing values ​​at individual outputs and inputs.",

        tutorial: "Tutorial and Instructions",
        tutorialText: "The application includes a tutorial and step-by-step instructions for new users.",

        projectName: "Project name",
        author: "Author",
        aboutText: "This graduation project presents an interactive logic circuit simulator that allows students and electronics and computer science enthusiasts to experiment with digital circuits in real time. Built in JavaScript, HTML and CSS, this tool uses the Konva.js library to visualize components and circuits on the canvas.",

        saveText: "Are you sure you want to continue without saving your project?",
        Save_project: "Save current project?",

        WelcomeTitle: "Logical Circuit Simulator",
        WelcomeText: "Welcome to LogicSim!  Whether you are a begginer or know something about digital logic. With an intuitive interface and an extensive library of components, you can try your ideas and watch logical circuits in action. Happy simulating!",

        ChangeSettings: "Change Settings",
        Tutorial1: "Simple change of the entire page settings. You can modify the color scheme, language, and many other settings for working in the editor.",
        
        CircuitEditor: "Working in the Editor",
        Tutorial2: "Users can zoom in and out of the view. It is also possible to move infinitely in all directions.",
        
        AddComponents: "Adding Components",
        Tutorial3: "Quick addition of components from the library. There are up to 32 unique components to choose from.",
        
        EditComponents: "Editing Components",
        Tutorial4: "Users can freely edit all components, change their position, rotation, and remove unnecessary components. Right click on the component to edit.",
        
        AddWires: "Connecting Components",
        Tutorial5: "Clicking on any two terminals creates a connection between the two components. If you are drawing a wire from output you can shape the connection by right clicking anywhere in the editor.",
        
        Simulate: "Circuit Simulation",
        Tutorial6: "Animated simulation of any logical circuit. The simulation starts and stops with just one click.",
        
        OscilloscopeSettings: "Oscilloscope and Signal Waveform",
        Tutorial7: "You can add any node to the oscilloscope by simply right-clicking on it. The signal can be adjusted by right-clicking on the oscilloscope.",
        
        SaveAndLoad: "Saving and Loading Circuits",
        Tutorial8: "The connected circuit can be easily saved in JSON format, which users can further modify in text form or load and edit in the editor.",
        
        GithubPage: "Open Source",
        Tutorial9: "The entire source code of the application is available on my GitHub page.",
        

        WireLoop: "Wire loop detected!",
        IncorrectTitle: "The title must be at least 4 characters long and less than 30!",
        CorrectTitle: "Title changed!",
        DownloadCompleted: "Circuit was downloaded correctly!",
        WrongOutput: "Output values are incorrectly formated!",
        WrongInput: "Incorrectly entered value!",
        EditDisabled: "Adding new components and deleting wires is not possible during simulation!",
    },
}
